title: Qi Xue
logo: /assets/headshot.jpeg
description: I am a policy professional with a robust background in econometric analysis and a strong commitment to evidence-based policymaking. My expertise spans environmental, agricultural, and public health sectors. I have collaborated with international organizations and lived and worked in diverse cultural settings. I excel at transforming complex data into actionable insights to inform policy decisions, thriving in dynamic, multicultural environments. My goal is to drive impactful change through data-driven strategies.
show_downloads: true
theme: jekyll-theme-minimal
