title: Qi Xue
logo: /assets/headshot.jpeg
description: I am a policy professional with a robust background in econometric analysis and a strong commitment to evidence-based policymaking.
show_downloads: true
theme: jekyll-theme-minimal
